"use client";

import { useRef } from "react";
import { useGSAP } from "@gsap/react";
import { ensureAnimationPlugins, gsap } from "@/lib/animation-runtime";
import { ModularConstruction } from "../ModularConstruction";

const roles=["Quantitative Researcher","Financial Engineer","Algorithmic Trader","AI & Financial Technology Developer"];
export function FounderScene(){const root=useRef<HTMLElement>(null);useGSAP(()=>{if(!ensureAnimationPlugins()||matchMedia("(prefers-reduced-motion: reduce)").matches)return;gsap.from(".modular-construction > span",{y:140,opacity:0,rotate:8,stagger:.06,scrollTrigger:{trigger:root.current,start:"top 70%",end:"bottom 45%",scrub:1}});},{scope:root});return <section ref={root} id="founder" className="founder-scene"><ModularConstruction/><div className="founder-content"><div className="founder-signal"><span>AH</span><small>FOUNDER / ARIMA FINANCE</small></div><div><p className="eyebrow">04 / FOUNDER &amp; COMPANY STORY</p><h2>Aryan Heidari</h2><div className="role-grid">{roles.map(role=><span key={role}>{role}</span>)}</div><p className="lead">Aryan Heidari founded Arima Finance to combine quantitative finance, artificial intelligence, financial engineering and technology within one integrated financial ecosystem.</p><p>His experience spans financial markets, investment research, portfolio management, trading systems, quantitative modelling and financial technology development.</p><div className="founder-pillars"><article><span>EXPERIENCE</span><strong>Financial markets &amp; investment analysis</strong></article><article><span>EDUCATION</span><strong>MSc Finance</strong></article><article><span>TECHNOLOGY</span><strong>Python, systems &amp; applied AI</strong></article><article id="research"><span>RESEARCH</span><strong>AI, digital assets &amp; market infrastructure</strong></article></div><p className="publication-note">A publication-approved professional portrait and reviewed public CV remain forthcoming. No unverified image or chronology is shown.</p></div></div></section>}
