// ─── Arima Universe — Mind Map Data Model ───
// 🧩 Complete Arima ecosystem mind map

import type { MindNode, ConnectionLine } from '@/types';

export const MIND_MAP_NODES: MindNode[] = [
  {
    id: 'root',
    label: 'ARIMA',
    type: 'root',
    x: 600,
    y: 400,
    children: ['financial-intelligence', 'investment-banking', 'projects-tech', 'portfolio-lab', 'engine', 'research', 'founder', 'arima-os'],
    parentId: null,
    depth: 0,
    description: 'Quantitative Intelligence',
    color: '#69c8ff',
  },
  {
    id: 'financial-intelligence',
    label: 'Financial Intelligence',
    type: 'branch',
    x: 200,
    y: 180,
    children: ['market-intelligence', 'corporate-finance', 'strategic-advisory', 'institutional-research'],
    parentId: 'root',
    depth: 1,
    description: 'Data-driven financial insight',
    color: '#f59e0b',
  },
  {
    id: 'investment-banking',
    label: 'Investment Banking',
    type: 'branch',
    x: 400,
    y: 120,
    children: ['ma-advisory', 'capital-markets', 'valuation', 'deal-structuring'],
    parentId: 'root',
    depth: 1,
    description: 'Capital markets & advisory',
    color: '#f59e0b',
  },
  {
    id: 'projects-tech',
    label: 'Projects & Technology',
    type: 'branch',
    x: 800,
    y: 120,
    children: ['ai-research', 'fintech', 'spatial-computing', 'research-projects'],
    parentId: 'root',
    depth: 1,
    description: 'Engineering the future of finance',
    color: '#06b6d4',
  },
  {
    id: 'portfolio-lab',
    label: 'Portfolio Lab',
    type: 'branch',
    x: 1000,
    y: 180,
    children: ['model-portfolio', 'quant-research', 'risk-intelligence', 'market-experiments'],
    parentId: 'root',
    depth: 1,
    description: 'Live-funded research environment',
    color: '#8b5cf6',
  },
  {
    id: 'engine',
    label: 'Arima Finance Engine',
    type: 'branch',
    x: 100,
    y: 400,
    children: ['market-analysis', 'risk-management', 'trade-lifecycle', 'signal-generation'],
    parentId: 'root',
    depth: 1,
    description: 'Flagship market intelligence system',
    color: '#69c8ff',
  },
  {
    id: 'research',
    label: 'Research',
    type: 'branch',
    x: 1100,
    y: 400,
    children: ['financial-modelling', 'company-analysis', 'scenario-analysis', 'investment-memoranda'],
    parentId: 'root',
    depth: 1,
    description: 'Institutional-grade research',
    color: '#a78bfa',
  },
  {
    id: 'founder',
    label: 'Founder',
    type: 'branch',
    x: 200,
    y: 620,
    children: ['aryan-heidari', 'avionics', 'finance-accounting', 'quantitative'],
    parentId: 'root',
    depth: 1,
    description: 'Aryan Heidari',
    color: '#60a5fa',
  },
  {
    id: 'arima-os',
    label: 'Arima OS',
    type: 'branch',
    x: 1000,
    y: 620,
    children: ['ecosystem', 'integration', 'intelligence-layer'],
    parentId: 'root',
    depth: 1,
    description: 'The operating system of finance',
    color: '#69c8ff',
  },
  // ─── Financial Intelligence children ───
  {
    id: 'market-intelligence',
    label: 'Market Intelligence',
    type: 'leaf',
    x: 50,
    y: 80,
    children: [],
    parentId: 'financial-intelligence',
    depth: 2,
    color: '#f59e0b',
  },
  {
    id: 'corporate-finance',
    label: 'Corporate Finance',
    type: 'leaf',
    x: 180,
    y: 60,
    children: [],
    parentId: 'financial-intelligence',
    depth: 2,
    color: '#f59e0b',
  },
  {
    id: 'strategic-advisory',
    label: 'Strategic Advisory',
    type: 'leaf',
    x: 320,
    y: 80,
    children: [],
    parentId: 'financial-intelligence',
    depth: 2,
    color: '#f59e0b',
  },
  {
    id: 'institutional-research',
    label: 'Institutional Research',
    type: 'leaf',
    x: 200,
    y: 40,
    children: [],
    parentId: 'financial-intelligence',
    depth: 2,
    color: '#f59e0b',
  },
  // ─── Investment Banking children ───
  {
    id: 'ma-advisory',
    label: 'M&A Advisory',
    type: 'leaf',
    x: 320,
    y: 30,
    children: [],
    parentId: 'investment-banking',
    depth: 2,
    color: '#f59e0b',
  },
  {
    id: 'capital-markets',
    label: 'Capital Markets',
    type: 'leaf',
    x: 400,
    y: 20,
    children: [],
    parentId: 'investment-banking',
    depth: 2,
    color: '#f59e0b',
  },
  {
    id: 'valuation',
    label: 'Valuation',
    type: 'leaf',
    x: 480,
    y: 30,
    children: [],
    parentId: 'investment-banking',
    depth: 2,
    color: '#f59e0b',
  },
  {
    id: 'deal-structuring',
    label: 'Deal Structuring',
    type: 'leaf',
    x: 400,
    y: 10,
    children: [],
    parentId: 'investment-banking',
    depth: 2,
    color: '#f59e0b',
  },
  // ─── Projects & Technology children ───
  {
    id: 'ai-research',
    label: 'AI Research',
    type: 'leaf',
    x: 720,
    y: 30,
    children: [],
    parentId: 'projects-tech',
    depth: 2,
    color: '#06b6d4',
  },
  {
    id: 'fintech',
    label: 'Financial Technology',
    type: 'leaf',
    x: 800,
    y: 20,
    children: [],
    parentId: 'projects-tech',
    depth: 2,
    color: '#06b6d4',
  },
  {
    id: 'spatial-computing',
    label: 'Spatial Computing',
    type: 'leaf',
    x: 880,
    y: 30,
    children: [],
    parentId: 'projects-tech',
    depth: 2,
    color: '#06b6d4',
  },
  {
    id: 'research-projects',
    label: 'Research Projects',
    type: 'leaf',
    x: 800,
    y: 10,
    children: [],
    parentId: 'projects-tech',
    depth: 2,
    color: '#06b6d4',
  },
  // ─── Portfolio Lab children ───
  {
    id: 'model-portfolio',
    label: 'Model Portfolio',
    type: 'leaf',
    x: 920,
    y: 80,
    children: [],
    parentId: 'portfolio-lab',
    depth: 2,
    color: '#8b5cf6',
  },
  {
    id: 'quant-research',
    label: 'Quantitative Research',
    type: 'leaf',
    x: 1000,
    y: 60,
    children: [],
    parentId: 'portfolio-lab',
    depth: 2,
    color: '#8b5cf6',
  },
  {
    id: 'risk-intelligence',
    label: 'Risk Intelligence',
    type: 'leaf',
    x: 1080,
    y: 80,
    children: [],
    parentId: 'portfolio-lab',
    depth: 2,
    color: '#8b5cf6',
  },
  {
    id: 'market-experiments',
    label: 'Market Experiments',
    type: 'leaf',
    x: 1000,
    y: 40,
    children: [],
    parentId: 'portfolio-lab',
    depth: 2,
    color: '#8b5cf6',
  },
  // ─── Engine children ───
  {
    id: 'market-analysis',
    label: 'Market Analysis',
    type: 'leaf',
    x: 20,
    y: 320,
    children: [],
    parentId: 'engine',
    depth: 2,
    color: '#69c8ff',
  },
  {
    id: 'risk-management',
    label: 'Risk Management',
    type: 'leaf',
    x: 100,
    y: 300,
    children: [],
    parentId: 'engine',
    depth: 2,
    color: '#69c8ff',
  },
  {
    id: 'trade-lifecycle',
    label: 'Trade Lifecycle',
    type: 'leaf',
    x: 180,
    y: 320,
    children: [],
    parentId: 'engine',
    depth: 2,
    color: '#69c8ff',
  },
  {
    id: 'signal-generation',
    label: 'Signal Generation',
    type: 'leaf',
    x: 100,
    y: 280,
    children: [],
    parentId: 'engine',
    depth: 2,
    color: '#69c8ff',
  },
  // ─── Research children ───
  {
    id: 'financial-modelling',
    label: 'Financial Modelling',
    type: 'leaf',
    x: 1020,
    y: 320,
    children: [],
    parentId: 'research',
    depth: 2,
    color: '#a78bfa',
  },
  {
    id: 'company-analysis',
    label: 'Company Analysis',
    type: 'leaf',
    x: 1100,
    y: 300,
    children: [],
    parentId: 'research',
    depth: 2,
    color: '#a78bfa',
  },
  {
    id: 'scenario-analysis',
    label: 'Scenario Analysis',
    type: 'leaf',
    x: 1180,
    y: 320,
    children: [],
    parentId: 'research',
    depth: 2,
    color: '#a78bfa',
  },
  {
    id: 'investment-memoranda',
    label: 'Investment Memoranda',
    type: 'leaf',
    x: 1100,
    y: 280,
    children: [],
    parentId: 'research',
    depth: 2,
    color: '#a78bfa',
  },
  // ─── Founder children ───
  {
    id: 'aryan-heidari',
    label: 'Aryan Heidari',
    type: 'leaf',
    x: 120,
    y: 700,
    children: [],
    parentId: 'founder',
    depth: 2,
    color: '#60a5fa',
  },
  {
    id: 'avionics',
    label: 'Avionics Engineering',
    type: 'leaf',
    x: 200,
    y: 720,
    children: [],
    parentId: 'founder',
    depth: 2,
    color: '#60a5fa',
  },
  {
    id: 'finance-accounting',
    label: 'Finance & Accounting',
    type: 'leaf',
    x: 280,
    y: 700,
    children: [],
    parentId: 'founder',
    depth: 2,
    color: '#60a5fa',
  },
  {
    id: 'quantitative',
    label: 'Quantitative Intelligence',
    type: 'leaf',
    x: 200,
    y: 680,
    children: [],
    parentId: 'founder',
    depth: 2,
    color: '#60a5fa',
  },
  // ─── Arima OS children ───
  {
    id: 'ecosystem',
    label: 'Ecosystem',
    type: 'leaf',
    x: 920,
    y: 700,
    children: [],
    parentId: 'arima-os',
    depth: 2,
    color: '#69c8ff',
  },
  {
    id: 'integration',
    label: 'Integration Layer',
    type: 'leaf',
    x: 1000,
    y: 720,
    children: [],
    parentId: 'arima-os',
    depth: 2,
    color: '#69c8ff',
  },
  {
    id: 'intelligence-layer',
    label: 'Intelligence Layer',
    type: 'leaf',
    x: 1080,
    y: 700,
    children: [],
    parentId: 'arima-os',
    depth: 2,
    color: '#69c8ff',
  },
];

export const MIND_MAP_CONNECTIONS: ConnectionLine[] = [
  // Root connections
  { id: 'c-root-fi', sourceId: 'root', targetId: 'financial-intelligence', animated: true },
  { id: 'c-root-ib', sourceId: 'root', targetId: 'investment-banking', animated: true },
  { id: 'c-root-pt', sourceId: 'root', targetId: 'projects-tech', animated: true },
  { id: 'c-root-pl', sourceId: 'root', targetId: 'portfolio-lab', animated: true },
  { id: 'c-root-en', sourceId: 'root', targetId: 'engine', animated: true },
  { id: 'c-root-re', sourceId: 'root', targetId: 'research', animated: true },
  { id: 'c-root-fo', sourceId: 'root', targetId: 'founder', animated: true },
  { id: 'c-root-os', sourceId: 'root', targetId: 'arima-os', animated: true },
  // Financial Intelligence
  { id: 'c-fi-mi', sourceId: 'financial-intelligence', targetId: 'market-intelligence' },
  { id: 'c-fi-cf', sourceId: 'financial-intelligence', targetId: 'corporate-finance' },
  { id: 'c-fi-sa', sourceId: 'financial-intelligence', targetId: 'strategic-advisory' },
  { id: 'c-fi-ir', sourceId: 'financial-intelligence', targetId: 'institutional-research' },
  // Investment Banking
  { id: 'c-ib-ma', sourceId: 'investment-banking', targetId: 'ma-advisory' },
  { id: 'c-ib-cm', sourceId: 'investment-banking', targetId: 'capital-markets' },
  { id: 'c-ib-va', sourceId: 'investment-banking', targetId: 'valuation' },
  { id: 'c-ib-ds', sourceId: 'investment-banking', targetId: 'deal-structuring' },
  // Projects & Technology
  { id: 'c-pt-ai', sourceId: 'projects-tech', targetId: 'ai-research' },
  { id: 'c-pt-ft', sourceId: 'projects-tech', targetId: 'fintech' },
  { id: 'c-pt-sc', sourceId: 'projects-tech', targetId: 'spatial-computing' },
  { id: 'c-pt-rp', sourceId: 'projects-tech', targetId: 'research-projects' },
  // Portfolio Lab
  { id: 'c-pl-mp', sourceId: 'portfolio-lab', targetId: 'model-portfolio' },
  { id: 'c-pl-qr', sourceId: 'portfolio-lab', targetId: 'quant-research' },
  { id: 'c-pl-ri', sourceId: 'portfolio-lab', targetId: 'risk-intelligence' },
  { id: 'c-pl-me', sourceId: 'portfolio-lab', targetId: 'market-experiments' },
  // Engine
  { id: 'c-en-ma', sourceId: 'engine', targetId: 'market-analysis' },
  { id: 'c-en-rm', sourceId: 'engine', targetId: 'risk-management' },
  { id: 'c-en-tl', sourceId: 'engine', targetId: 'trade-lifecycle' },
  { id: 'c-en-sg', sourceId: 'engine', targetId: 'signal-generation' },
  // Research
  { id: 'c-re-fm', sourceId: 'research', targetId: 'financial-modelling' },
  { id: 'c-re-ca', sourceId: 'research', targetId: 'company-analysis' },
  { id: 'c-re-sa', sourceId: 'research', targetId: 'scenario-analysis' },
  { id: 'c-re-im', sourceId: 'research', targetId: 'investment-memoranda' },
  // Founder
  { id: 'c-fo-ah', sourceId: 'founder', targetId: 'aryan-heidari' },
  { id: 'c-fo-av', sourceId: 'founder', targetId: 'avionics' },
  { id: 'c-fo-fa', sourceId: 'founder', targetId: 'finance-accounting' },
  { id: 'c-fo-qi', sourceId: 'founder', targetId: 'quantitative' },
  // Arima OS
  { id: 'c-os-ec', sourceId: 'arima-os', targetId: 'ecosystem' },
  { id: 'c-os-in', sourceId: 'arima-os', targetId: 'integration' },
  { id: 'c-os-il', sourceId: 'arima-os', targetId: 'intelligence-layer' },
];