import Link from 'next/link';
import type { PortfolioSnapshot } from '@/data/portfolio-lab';
import { currency, date, percent } from './format';
import { PortfolioLabNavigation } from './PortfolioLabNavigation';
import { EmptyPortfolioState, UnavailablePortfolioState } from './PortfolioDataState';
import { VoiceDock } from '@/components/executive/VoiceDock';

const sections = [
  ['overview', 'Overview'], ['performance', 'Performance'], ['holdings', 'Holdings'], ['transactions', 'Transactions'], ['risk', 'Risk Analytics'], ['allocation', 'Allocation'], ['cash-flow', 'Cash Flow'], ['ai-analyst', 'AI Portfolio Analyst'], ['reports', 'Reports'], ['settings', 'Account Settings'],
] as const;
type Section = (typeof sections)[number][0];

function StateNotice({ snapshot }: { snapshot: PortfolioSnapshot }) {
  if (snapshot.account.dataStatus !== 'stale') return null;
  return <div className="lab-state lab-state-stale"><span>Data status</span><strong>Last verified {date(snapshot.account.updatedAt)}</strong><p>Market values are shown from the latest available valuation snapshot.</p></div>;
}
function Metric({ label, value, trend }: { label: string; value: string; trend?: number }) {
  return <article className="lab-metric"><span>{label}</span><strong>{value}</strong>{trend !== undefined && <small className={trend >= 0 ? 'positive' : 'negative'}>{percent(trend)} period return</small>}</article>;
}
function Panel({ eyebrow, title, children }: { eyebrow?: string; title: string; children: React.ReactNode }) { return <section className="lab-panel">{eyebrow && <p className="lab-eyebrow">{eyebrow}</p>}<h2>{title}</h2>{children}</section>; }
function AllocationBars({ data }: { data: PortfolioSnapshot['allocation']['assetClasses'] }) { return <div className="allocation-list">{data.map((item) => <div key={item.label}><div><span>{item.label}</span><strong>{item.value.toFixed(1)}%</strong></div><i><b style={{ width: `${item.value}%`, background: item.colour }} /></i></div>)}</div>; }
function PerformanceLine({ performance }: { performance: PortfolioSnapshot['performance'] }) { const min = Math.min(...performance.flatMap((point) => [point.portfolioValue, point.benchmarkValue])); const max = Math.max(...performance.flatMap((point) => [point.portfolioValue, point.benchmarkValue])); const line = (key: 'portfolioValue' | 'benchmarkValue') => performance.map((point, index) => `${(index / (performance.length - 1)) * 100},${100 - ((point[key] - min) / (max - min)) * 92}`).join(' '); return <div className="lab-chart"><div className="chart-key"><span><i className="portfolio-line" />Portfolio</span><span><i className="benchmark-line" />Benchmark</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Portfolio performance chart"><polyline points={line('benchmarkValue')} className="chart-benchmark"/><polyline points={line('portfolioValue')} className="chart-portfolio"/></svg><div className="chart-axis">{performance.filter((_, index) => index % 2 === 0).map((item) => <span key={item.date}>{new Intl.DateTimeFormat('en-GB',{month:'short'}).format(new Date(item.date))}</span>)}</div></div>; }

function Overview({ snapshot }: { snapshot: PortfolioSnapshot }) { const { summary, portfolio, holdings, allocation } = snapshot; return <><div className="lab-hero"><div><p className="lab-eyebrow">Portfolio intelligence / {portfolio.id}</p><h1>{portfolio.name}</h1><p>Institutional clarity for a considered investment mandate.</p></div><StateNotice snapshot={snapshot} /></div><div className="metric-grid"><Metric label="Total portfolio value" value={currency(summary.totalValue, portfolio.baseCurrency)} trend={summary.dailyReturn}/><Metric label="Invested capital" value={currency(summary.investedValue, portfolio.baseCurrency)} /><Metric label="Since inception" value={percent(summary.totalReturn)} trend={summary.totalReturn}/><Metric label="Liquidity reserve" value={currency(summary.cashBalance, portfolio.baseCurrency)} /></div><div className="lab-layout"><Panel eyebrow="Trajectory" title="Portfolio value"><PerformanceLine performance={snapshot.performance}/></Panel><Panel eyebrow="Composition" title="Capital allocation"><AllocationBars data={allocation.assetClasses}/></Panel></div><Panel eyebrow="Positions" title="Largest holdings"><div className="holding-strip">{holdings.slice(0,4).map((holding) => <div key={holding.id}><span>{holding.symbol}</span><strong>{currency(holding.marketValue, portfolio.baseCurrency)}</strong><small>{(holding.weight * 100).toFixed(1)}% of portfolio</small></div>)}</div></Panel></>; }
function Performance({ snapshot }: { snapshot: PortfolioSnapshot }) { const { summary, portfolio } = snapshot; if (snapshot.performance.length < 2) return <UnavailablePortfolioState title="Performance history is unavailable" detail="The portfolio provider requires at least two valuation points to calculate performance."/>; return <><div className="lab-hero"><div><p className="lab-eyebrow">Performance attribution</p><h1>Measured through every market condition.</h1></div><StateNotice snapshot={snapshot}/></div><div className="metric-grid"><Metric label="Daily return" value={percent(summary.dailyReturn)} trend={summary.dailyReturn}/><Metric label="Weekly return" value={percent(summary.weeklyReturn)} trend={summary.weeklyReturn}/><Metric label="Monthly return" value={percent(summary.monthlyReturn)} trend={summary.monthlyReturn}/><Metric label="Benchmark" value={portfolio.benchmark}/></div><Panel eyebrow="Since inception" title="Portfolio versus benchmark"><PerformanceLine performance={snapshot.performance}/><div className="performance-foot"><span>Portfolio total return <b>{percent(summary.totalReturn)}</b></span><span>Benchmark return <b>{percent((snapshot.performance.at(-1)!.benchmarkValue / snapshot.performance[0].benchmarkValue) - 1)}</b></span></div></Panel></>; }
function Holdings({ snapshot }: { snapshot: PortfolioSnapshot }) { if (!snapshot.holdings.length) return <EmptyPortfolioState title="No holdings are available" detail="Open positions will appear here once the portfolio provider supplies holdings data."/>; return <><div className="lab-hero"><div><p className="lab-eyebrow">Portfolio inventory</p><h1>Holdings, exposed with precision.</h1></div><StateNotice snapshot={snapshot}/></div><Panel title="Open positions"><div className="lab-table"><div className="lab-row lab-table-head"><span>Instrument</span><span>Weight</span><span>Market value</span><span>Total return</span></div>{snapshot.holdings.map((holding) => <div className="lab-row" key={holding.id}><span><b>{holding.symbol}</b><small>{holding.name}</small></span><span>{(holding.weight * 100).toFixed(1)}%</span><span>{currency(holding.marketValue,snapshot.portfolio.baseCurrency)}</span><span className={holding.totalReturn >= 0 ? 'positive' : 'negative'}>{percent(holding.totalReturn)}</span></div>)}</div></Panel></>; }
function Transactions({ snapshot }: { snapshot: PortfolioSnapshot }) { if (!snapshot.transactions.length) return <EmptyPortfolioState title="No transactions are available" detail="Activity will appear here when the portfolio provider supplies transaction data."/>; return <><div className="lab-hero"><div><p className="lab-eyebrow">Activity ledger</p><h1>Every decision, accounted for.</h1></div><StateNotice snapshot={snapshot}/></div><Panel title="Recent transactions"><div className="lab-table"><div className="lab-row lab-table-head"><span>Date / type</span><span>Instrument</span><span>Status</span><span>Amount</span></div>{snapshot.transactions.map((transaction) => <div className="lab-row" key={transaction.id}><span><b>{date(transaction.date)}</b><small>{transaction.type}</small></span><span>{transaction.symbol ? `${transaction.symbol} · ` : ''}{transaction.description}</span><span><em>{transaction.status}</em></span><span className={transaction.amount >= 0 ? 'positive' : 'negative'}>{currency(transaction.amount,snapshot.portfolio.baseCurrency)}</span></div>)}</div></Panel></>; }
function Risk({ snapshot }: { snapshot: PortfolioSnapshot }) { const { risk } = snapshot; return <><div className="lab-hero"><div><p className="lab-eyebrow">Risk intelligence</p><h1>Risk is visible before it matters.</h1></div><StateNotice snapshot={snapshot}/></div><div className="metric-grid"><Metric label="Risk score" value={`${risk.riskScore} / 100`}/><Metric label="Annualised volatility" value={percent(risk.volatility)}/><Metric label="Sharpe ratio" value={risk.sharpeRatio.toFixed(2)}/><Metric label="Maximum drawdown" value={percent(risk.maxDrawdown)}/></div><Panel eyebrow="Factor monitor" title="Portfolio sensitivity"><div className="risk-grid">{risk.factors.map((factor) => <div key={factor.label}><span>{factor.label}</span><strong>{factor.assessment}</strong><i><b style={{ width:`${factor.value}%` }}/></i></div>)}</div><div className="risk-note">Estimated one-day value at risk: <b>{currency(risk.valueAtRisk,snapshot.portfolio.baseCurrency)}</b> · Concentration classification: <b>{risk.concentrationRisk}</b></div></Panel></>; }
function Allocation({ snapshot }: { snapshot: PortfolioSnapshot }) { return <><div className="lab-hero"><div><p className="lab-eyebrow">Exposure map</p><h1>Capital distributed with intent.</h1></div><StateNotice snapshot={snapshot}/></div><div className="lab-layout"><Panel eyebrow="Asset class" title="Strategic allocation"><AllocationBars data={snapshot.allocation.assetClasses}/></Panel><Panel eyebrow="Region" title="Geographic exposure"><AllocationBars data={snapshot.allocation.regions}/></Panel></div><Panel eyebrow="Sector" title="Underlying drivers"><AllocationBars data={snapshot.allocation.sectors}/></Panel></>; }
function CashFlow({ snapshot }: { snapshot: PortfolioSnapshot }) { return <><div className="lab-hero"><div><p className="lab-eyebrow">Capital movement</p><h1>Liquidity, with a complete audit trail.</h1></div><StateNotice snapshot={snapshot}/></div><Panel title="Cash flow history"><div className="cash-list">{snapshot.cashFlow.map((flow) => <div key={`${flow.date}-${flow.note}`}><span>{date(flow.date)}</span><strong>{flow.type}</strong><p>{flow.note}</p><b className={flow.amount >= 0 ? 'positive' : 'negative'}>{currency(flow.amount,snapshot.portfolio.baseCurrency)}</b></div>)}</div></Panel></>; }
function AiAnalyst({ snapshot }: { snapshot: PortfolioSnapshot }) { const { aiAnalysis } = snapshot; return <><div className="lab-hero"><div><p className="lab-eyebrow">Arima signal / confidence {(aiAnalysis.confidence * 100).toFixed(0)}%</p><h1>An intelligent second perspective.</h1><p>Generated from the portfolio snapshot; recommendations are research prompts, not investment advice.</p></div><StateNotice snapshot={snapshot}/></div><div className="lab-layout"><Panel eyebrow="Market context" title="Current read"><p className="analysis-copy">{aiAnalysis.marketView}</p></Panel><Panel eyebrow="Portfolio context" title="Mandate read"><p className="analysis-copy">{aiAnalysis.portfolioView}</p></Panel></div><Panel eyebrow="Suggested attention" title="Analyst notes"><div className="action-list">{aiAnalysis.actions.map((action) => <div key={action.title}><em>{action.priority}</em><h3>{action.title}</h3><p>{action.detail}</p></div>)}</div></Panel></>; }
function Reports({ snapshot }: { snapshot: PortfolioSnapshot }) { return <><div className="lab-hero"><div><p className="lab-eyebrow">Portfolio archive</p><h1>Evidence, prepared for review.</h1></div><StateNotice snapshot={snapshot}/></div><Panel title="Available reports"><div className="report-list">{snapshot.reports.map((report) => <div key={report.id}><div><strong>{report.name}</strong><span>{report.period}</span></div><em className={`report-${report.status.toLowerCase()}`}>{report.status}</em><button disabled={report.status !== 'Ready'}>{report.status === 'Ready' ? 'View report ↗' : 'Unavailable'}</button></div>)}</div><p className="lab-unavailable">Report delivery is a presentation placeholder. Document generation will connect when the reporting data service is available.</p></Panel></>; }
function Settings({ snapshot }: { snapshot: PortfolioSnapshot }) { const { portfolio, account } = snapshot; return <><div className="lab-hero"><div><p className="lab-eyebrow">Workspace configuration</p><h1>Portfolio mandate.</h1></div><StateNotice snapshot={snapshot}/></div><Panel title="Account details"><dl className="details-grid"><div><dt>Portfolio owner</dt><dd>{portfolio.owner}</dd></div><div><dt>Base currency</dt><dd>{portfolio.baseCurrency}</dd></div><div><dt>Benchmark</dt><dd>{portfolio.benchmark}</dd></div><div><dt>Risk profile</dt><dd>{portfolio.riskProfile}</dd></div><div><dt>Advisor</dt><dd>{account.advisor}</dd></div><div><dt>Reporting cadence</dt><dd>{account.reportingFrequency}</dd></div></dl></Panel><div className="lab-state"><span>Integration status</span><strong>Mock portfolio provider active</strong><p>This workspace is ready for an Excel or API provider to replace the current data source.</p></div></>; }

const page: Record<Section, (props: { snapshot: PortfolioSnapshot }) => React.ReactNode> = { overview: Overview, performance: Performance, holdings: Holdings, transactions: Transactions, risk: Risk, allocation: Allocation, 'cash-flow': CashFlow, 'ai-analyst': AiAnalyst, reports: Reports, settings: Settings };
export function isLabSection(value: string): value is Section { return sections.some(([id]) => id === value); }
export function PortfolioLabView({ snapshot, section = 'overview' }: { snapshot: PortfolioSnapshot; section?: Section }) { const Content = page[section]; return <main className="portfolio-lab"><aside className="lab-sidebar"><Link className="lab-mark" href="/"><i>AF</i><span>ARIMA<br/>FINANCE</span></Link><div className="lab-nav-label">Portfolio Lab</div><PortfolioLabNavigation sections={sections}/><div className="lab-sidebar-foot"><span>Client workspace</span><strong>{snapshot.portfolio.owner}</strong></div></aside><section className="lab-content"><header className="lab-topbar"><div><span>Portfolio Lab</span><b>/{section.replace('-', ' ')}</b></div><div><i className={snapshot.account.dataStatus} /> {snapshot.account.dataStatus === 'stale' ? 'Snapshot data' : 'Live valuation'}</div></header><div className="lab-build-marker" role="status"><strong>Portfolio Lab Build Active</strong><span>Holdings count: {snapshot.holdings.length}</span><span>Transactions count: {snapshot.transactions.length}</span></div><Content snapshot={snapshot}/><footer className="lab-footer">Arima Finance · Data shown for architecture demonstration only · Not investment advice</footer></section><VoiceDock context="portfolio" /></main>; }
